%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/jazzy/.*$
%global __requires_exclude_from ^/opt/ros/jazzy/.*$

%global __cmake_in_source_build 1

Name:           ros-jazzy-sm-panda-cl-moveit2z-cb-inventory
Version:        3.0.1
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS sm_panda_cl_moveit2z_cb_inventory package

License:        Apache-2.0 and MyLicense
Source0:        %{name}-%{version}.tar.gz

Requires:       boost-devel
Requires:       ros-jazzy-cl-keyboard
Requires:       ros-jazzy-cl-moveit2z
Requires:       ros-jazzy-cl-ros2-timer
Requires:       ros-jazzy-controller-manager
Requires:       ros-jazzy-joint-state-broadcaster
Requires:       ros-jazzy-joint-trajectory-controller
Requires:       ros-jazzy-moveit
Requires:       ros-jazzy-moveit-planners-chomp
Requires:       ros-jazzy-moveit-planners-ompl
Requires:       ros-jazzy-moveit-plugins
Requires:       ros-jazzy-moveit-resources-panda-moveit-config
Requires:       ros-jazzy-moveit-ros-robot-interaction
Requires:       ros-jazzy-moveit-simple-controller-manager
Requires:       ros-jazzy-moveit-visual-tools
Requires:       ros-jazzy-pilz-industrial-motion-planner
Requires:       ros-jazzy-rclcpp
Requires:       ros-jazzy-robot-state-publisher
Requires:       ros-jazzy-smacc2
Requires:       yaml-cpp-devel
Requires:       ros-jazzy-ros-workspace
BuildRequires:  boost-devel
BuildRequires:  ros-jazzy-ament-cmake
BuildRequires:  ros-jazzy-cl-keyboard
BuildRequires:  ros-jazzy-cl-moveit2z
BuildRequires:  ros-jazzy-cl-ros2-timer
BuildRequires:  ros-jazzy-controller-manager
BuildRequires:  ros-jazzy-joint-state-broadcaster
BuildRequires:  ros-jazzy-moveit
BuildRequires:  ros-jazzy-moveit-planners-chomp
BuildRequires:  ros-jazzy-moveit-planners-ompl
BuildRequires:  ros-jazzy-moveit-plugins
BuildRequires:  ros-jazzy-moveit-resources-panda-moveit-config
BuildRequires:  ros-jazzy-moveit-ros-robot-interaction
BuildRequires:  ros-jazzy-moveit-simple-controller-manager
BuildRequires:  ros-jazzy-moveit-visual-tools
BuildRequires:  ros-jazzy-pilz-industrial-motion-planner
BuildRequires:  ros-jazzy-rclcpp
BuildRequires:  ros-jazzy-robot-state-publisher
BuildRequires:  ros-jazzy-smacc2
BuildRequires:  yaml-cpp-devel
BuildRequires:  ros-jazzy-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
The sm_panda_cl_moveit2z_cb_inventory package

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jazzy/setup.sh" ]; then . "/opt/ros/jazzy/setup.sh"; fi
mkdir -p .obj-%{_target_platform} && cd .obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/jazzy" \
    -DAMENT_PREFIX_PATH="/opt/ros/jazzy" \
    -DCMAKE_PREFIX_PATH="/opt/ros/jazzy" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jazzy/setup.sh" ]; then . "/opt/ros/jazzy/setup.sh"; fi
%make_install -C .obj-%{_target_platform}

%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C .obj-%{_target_platform} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jazzy/setup.sh" ]; then . "/opt/ros/jazzy/setup.sh"; fi
CTEST_OUTPUT_ON_FAILURE=1 \
    %make_build -C .obj-%{_target_platform} $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/jazzy

%changelog
* Sun Nov 16 2025 SMACC2 is cool <smacc2@smacc2.cool> - 3.0.1-1
- Autogenerated by Bloom

